version: "3.8"
services:
  redis:
    container_name: duren-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass duren
    volumes:
      - redis:/data

volumes:
  redis:
